### ISSUE TITLE
TypeError from decode_abbreviation

### ISSUE THREAD

**Issue by afrigeri** [ggmichael/craterstats#2]
From b629e741d11d731f4d734961fd3fdbd371efbff3 when running the demo I get this:

```
Traceback (most recent call last):
  File "/Users/alf/gitwrk/craterstats/src/craterstats/cli.py", line 102, in decode_abbreviation
    return np.clip(int(v) - int(not zero_based), 0, len(s))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alf/gitwrk/craterstats/src/craterstats.py", line 5, in <module>
    cli.main(None)
  File "/Users/alf/gitwrk/craterstats/src/craterstats/cli.py", line 289, in main
    cps_dict = construct_cps_dict(args, c, f)
  File "/Users/alf/gitwrk/craterstats/src/craterstats/cli.py", line 117, in construct_cps_dict
    cpset['presentation'] = cst.PRESENTATIONS[decode_abbreviation(cst.PRESENTATIONS, args.presentation)]
  File "/Users/alf/gitwrk/craterstats/src/craterstats/cli.py", line 104, in decode_abbreviation
    regex = '(?i)' + '.*'.join(v)
TypeError: can only join an iterable
```

checking out previous commits, demo works flawlessly.

**Comment by ggmichael** [comment]
Hi Alessandro - thanks for taking a look. That issue should be fixed now.

**Comment by afrigeri** [comment]
Oh yes! tested 0d3261c01a79a3e88b30b0e82011ad7238caa038 and now demos work perfectly - thanks Greg!
